"""
Brain Service for Friday AI.
Handles creating notes in the Obsidian brain following the Operating Manual rules.
"""
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional, List
import yaml
from app.core.config import settings
from app.core.logging import logger


class BrainService:
    """
    Service for creating and managing notes in the Obsidian brain.
    
    Follows the Obsidian Operating Manual rules:
    - Uses proper folder structure
    - Applies correct tags
    - Uses templates for consistent formatting
    """
    
    def __init__(self):
        """Initialize brain service with paths."""
        self.brain_path = settings.brain_path
        self.inbox_path = self.brain_path / "0. Overview" / "0.1 Inbox"
        self.notes_path = settings.vault_path  # 1. Notes
        self.friday_path = settings.friday_path  # 5. Friday
        self.memories_path = settings.memories_path
        self.journal_path = settings.journal_path
        self.reports_path = settings.reports_path
        
        # Ensure directories exist
        for path in [self.inbox_path, self.memories_path, self.journal_path, self.reports_path]:
            path.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"Brain service initialized: {self.brain_path}")
    
    def _generate_id(self) -> str:
        """Generate a short unique ID."""
        return str(uuid.uuid4())[:8]
    
    def _sanitize_filename(self, text: str) -> str:
        """Convert text to valid filename."""
        import re
        text = text[:60]
        text = re.sub(r'[<>:"/\\|?*\n\r]', '', text)
        text = text.strip()
        text = re.sub(r'\s+', ' ', text)
        return text if text else "untitled"
    
    def create_inbox_note(
        self,
        title: str,
        content: str,
        topic: Optional[str] = None,
        additional_tags: Optional[List[str]] = None,
    ) -> Path:
        """
        Create a new note in the Inbox folder.
        
        Used for ideas, discussion topics, or anything Friday wants to capture
        for later review by the user.
        
        Args:
            title: Note title
            content: Note content (markdown)
            topic: Optional topic for context
            additional_tags: Additional tags beyond the defaults
            
        Returns:
            Path to created file
        """
        note_id = self._generate_id()
        created = datetime.now()
        
        # Build tags following the Operating Manual
        tags = ["area/friday", "extra/idea"]
        if additional_tags:
            tags.extend(additional_tags)
        
        # Build frontmatter
        frontmatter = {
            "tags": tags,
            "aliases": [],
            "related": [],
            "id": note_id,
            "created": created.strftime("%Y-%m-%d"),
            "source": "friday-ai",
            "status": "inbox",
        }
        
        yaml_str = yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True, sort_keys=False)
        
        # Build note content following Friday Idea template
        note = f"""---
{yaml_str.strip()}
---

# {title}

{content}

---

## Context

- **Generated by:** Friday AI
- **Date:** {created.strftime("%Y-%m-%d %H:%M")}
- **Conversation topic:** {topic or "General conversation"}

## Next Steps

- [ ] Review and refine
- [ ] Add connections
- [ ] Move to appropriate folder
"""
        
        # Create file
        filename = f"{self._sanitize_filename(title)}.md"
        filepath = self.inbox_path / filename
        
        # Handle duplicates
        counter = 1
        while filepath.exists():
            filename = f"{self._sanitize_filename(title)} {counter}.md"
            filepath = self.inbox_path / filename
            counter += 1
        
        filepath.write_text(note, encoding="utf-8")
        logger.info(f"Created inbox note: {filepath}")
        
        return filepath
    
    def create_journal_entry(
        self,
        date: datetime,
        sleep_summary: str = "",
        recovery_summary: str = "",
        activity_summary: str = "",
        calendar_events: str = "",
        insights: str = "",
    ) -> Path:
        """
        Create a daily journal entry in the Friday Journal folder.
        
        Args:
            date: Date for the journal entry
            sleep_summary: Sleep quality summary
            recovery_summary: Recovery/HRV summary
            activity_summary: Activity/steps summary
            calendar_events: Calendar events for the day
            insights: AI-generated insights
            
        Returns:
            Path to created file
        """
        note_id = self._generate_id()
        date_str = date.strftime("%Y-%m-%d")
        
        # Build tags
        tags = ["area/friday", "time/daily", "extra/journal"]
        
        # Build frontmatter
        frontmatter = {
            "tags": tags,
            "aliases": [],
            "related": [],
            "id": note_id,
            "date": date_str,
        }
        
        yaml_str = yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True, sort_keys=False)
        
        # Build note content
        note = f"""---
{yaml_str.strip()}
---

# Friday Journal - {date_str}

## Health Summary

### Sleep
{sleep_summary or "_No sleep data available_"}

### Recovery
{recovery_summary or "_No recovery data available_"}

### Activity
{activity_summary or "_No activity data available_"}

## Calendar

{calendar_events or "_No events scheduled_"}

## Insights

{insights or "_No insights generated_"}

---

## Connections

- **Related Daily Notes:** [[{date_str}]]
- **Previous Journal:** 
"""
        
        # Create file
        filename = f"Friday Journal {date_str}.md"
        filepath = self.journal_path / filename
        
        # Overwrite if exists (daily journal)
        filepath.write_text(note, encoding="utf-8")
        logger.info(f"Created journal entry: {filepath}")
        
        return filepath
    
    def create_weekly_report(
        self,
        week_start: datetime,
        week_end: datetime,
        summary: str = "",
        sleep_metrics: str = "",
        training_metrics: str = "",
        activity_metrics: str = "",
        achievements: str = "",
        improvements: str = "",
        recommendations: str = "",
    ) -> Path:
        """
        Create a weekly report in the Friday Reports folder.
        
        Args:
            week_start: Start of the week
            week_end: End of the week
            summary: Week summary
            sleep_metrics: Sleep quality metrics
            training_metrics: Training/recovery metrics
            activity_metrics: Activity trends
            achievements: Notable achievements
            improvements: Areas for improvement
            recommendations: AI recommendations
            
        Returns:
            Path to created file
        """
        note_id = self._generate_id()
        week_number = week_start.isocalendar()[1]
        year = week_start.year
        
        # Build tags
        tags = ["area/friday", "time/weekly", "extra/report"]
        
        # Build frontmatter
        frontmatter = {
            "tags": tags,
            "aliases": [],
            "related": [],
            "id": note_id,
            "date": datetime.now().strftime("%Y-%m-%d"),
            "period_start": week_start.strftime("%Y-%m-%d"),
            "period_end": week_end.strftime("%Y-%m-%d"),
        }
        
        yaml_str = yaml.dump(frontmatter, default_flow_style=False, allow_unicode=True, sort_keys=False)
        
        # Build note content
        note = f"""---
{yaml_str.strip()}
---

# Friday Report - {year} Week {week_number}

## Summary

{summary or "_No summary available_"}

## Health Metrics

### Sleep Quality
{sleep_metrics or "_No sleep data available_"}

### Training & Recovery
{training_metrics or "_No training data available_"}

### Activity Trends
{activity_metrics or "_No activity data available_"}

## Achievements

{achievements or "_No achievements recorded_"}

## Areas for Improvement

{improvements or "_No improvements identified_"}

## Recommendations

{recommendations or "_No recommendations available_"}

---

## Connections

- **Related Weekly Note:** [[{year}-W{week_number:02d}]]
- **Previous Report:** 
"""
        
        # Create file
        filename = f"Friday Report {year}-W{week_number:02d}.md"
        filepath = self.reports_path / filename
        
        # Overwrite if exists (weekly report)
        filepath.write_text(note, encoding="utf-8")
        logger.info(f"Created weekly report: {filepath}")
        
        return filepath


# Singleton instance
brain_service = BrainService()
